// GENERATED by scripts/generate_bike_map.py - do not hand-edit.
// LED maps for Cody's bike: the 4-chevron panel (Fusion 'radrunner'
// design) and the frame wrap glow strip, in one shared coordinate
// system. x: 0 rear of the BIKE -> 255 nose (the panel spans 23..66,
// anchored by the chevrons starting 75% of the way down each side).
// The frame strip's pixels carry its real route along the frame
// (head-tube dive, low rail, rear wrap - a waypoint polyline in the
// generator), so y is true height: 0 at the low rail, 255 at the
// head tube. Panel y stays 0 bottom -> 255 top across its own
// height. seg: chevron 0 (rear) .. 3 (front); the frame's fore-aft
// quarter-bands carry the seg of the chevron they step with.
// vdist: 0 at a segment's focal point (chevron vertex / band front
// edge), 255 at its far end (leg tip / band rear edge).
#ifndef CODYS_BIKE_MAP_H
#define CODYS_BIKE_MAP_H

#include <LightShow.h>

#define CODYS_BIKE_LED_COUNT 50
#define CODYS_BIKE_SEGMENTS 4

const PanelPixel CODYS_BIKE_MAP[CODYS_BIKE_LED_COUNT] = {
    { 47, 255, 3, 255},  // led  0  (  1.475,   7.575) cm
    { 50, 234, 3, 212},  // led  1  (  2.713,   6.338) cm
    { 53, 212, 3, 170},  // led  2  (  3.950,   5.100) cm
    { 56, 191, 3, 128},  // led  3  (  5.188,   3.863) cm
    { 60, 170, 3,  85},  // led  4  (  6.425,   2.625) cm
    { 63, 149, 3,  42},  // led  5  (  7.663,   1.387) cm
    { 66, 128, 3,   0},  // led  6  (  8.900,   0.150) cm
    { 63, 106, 3,  42},  // led  7  (  7.663,  -1.088) cm
    { 60,  85, 3,  85},  // led  8  (  6.425,  -2.325) cm
    { 56,  64, 3, 128},  // led  9  (  5.188,  -3.563) cm
    { 53,  43, 3, 170},  // led 10  (  3.950,  -4.800) cm
    { 50,  21, 3, 212},  // led 11  (  2.713,  -6.037) cm
    { 47,   0, 3, 255},  // led 12  (  1.475,  -7.275) cm
    { 38,   0, 2, 255},  // led 13  ( -2.125,  -7.275) cm
    { 41,  21, 2, 212},  // led 14  ( -0.888,  -6.037) cm
    { 44,  43, 2, 170},  // led 15  (  0.350,  -4.800) cm
    { 47,  64, 2, 128},  // led 16  (  1.587,  -3.563) cm
    { 51,  85, 2,  85},  // led 17  (  2.825,  -2.325) cm
    { 54, 106, 2,  42},  // led 18  (  4.062,  -1.088) cm
    { 57, 128, 2,   0},  // led 19  (  5.300,   0.150) cm
    { 54, 149, 2,  42},  // led 20  (  4.062,   1.387) cm
    { 51, 170, 2,  85},  // led 21  (  2.825,   2.625) cm
    { 47, 191, 2, 128},  // led 22  (  1.587,   3.863) cm
    { 44, 212, 2, 170},  // led 23  (  0.350,   5.100) cm
    { 41, 234, 2, 212},  // led 24  ( -0.888,   6.338) cm
    { 38, 255, 2, 255},  // led 25  ( -2.125,   7.575) cm
    { 29, 255, 1, 255},  // led 26  ( -5.725,   7.575) cm
    { 32, 234, 1, 212},  // led 27  ( -4.487,   6.338) cm
    { 35, 212, 1, 170},  // led 28  ( -3.250,   5.100) cm
    { 38, 191, 1, 128},  // led 29  ( -2.013,   3.863) cm
    { 42, 170, 1,  85},  // led 30  ( -0.775,   2.625) cm
    { 45, 149, 1,  42},  // led 31  (  0.462,   1.387) cm
    { 48, 128, 1,   0},  // led 32  (  1.700,   0.150) cm
    { 45, 106, 1,  42},  // led 33  (  0.462,  -1.088) cm
    { 42,  85, 1,  85},  // led 34  ( -0.775,  -2.325) cm
    { 38,  64, 1, 128},  // led 35  ( -2.013,  -3.563) cm
    { 35,  43, 1, 170},  // led 36  ( -3.250,  -4.800) cm
    { 32,  21, 1, 212},  // led 37  ( -4.487,  -6.037) cm
    { 29,   0, 1, 255},  // led 38  ( -5.725,  -7.275) cm
    { 23,  21, 0, 255},  // led 39  ( -8.088,  -6.037) cm
    { 26,  43, 0, 204},  // led 40  ( -6.850,  -4.800) cm
    { 29,  64, 0, 153},  // led 41  ( -5.613,  -3.563) cm
    { 33,  85, 0, 102},  // led 42  ( -4.375,  -2.325) cm
    { 36, 106, 0,  51},  // led 43  ( -3.138,  -1.088) cm
    { 39, 128, 0,   0},  // led 44  ( -1.900,   0.150) cm
    { 36, 149, 0,  51},  // led 45  ( -3.138,   1.387) cm
    { 33, 170, 0, 102},  // led 46  ( -4.375,   2.625) cm
    { 29, 191, 0, 153},  // led 47  ( -5.613,   3.863) cm
    { 26, 212, 0, 204},  // led 48  ( -6.850,   5.100) cm
    { 23, 234, 0, 255},  // led 49  ( -8.088,   6.338) cm
};

// Logical rear->front playback order (see setRenderOrder):
// streams, meteors, cylon etc. travel the bike's axis instead
// of snaking the wiring path.
const uint16_t CODYS_BIKE_STREAM_ORDER[CODYS_BIKE_LED_COUNT] = {
    39, 49, 40, 48, 38, 26, 41, 47, 37, 27,
    42, 46, 36, 28, 43, 45, 13, 25, 35, 29,
    44, 14, 24, 34, 30, 15, 23, 33, 31, 12,
     0, 16, 22, 32, 11,  1, 17, 21, 10,  2,
    18, 20,  9,  3, 19,  8,  4,  7,  5,  6,
};

// Frame wrap glow strip: 5 cm/pixel (3 LEDs each), 50 pixels
// (25 per side, count dialled in on the bike). Pixels walk
// the frame route at even arc steps: head tube down to the low
// rail, flat to the chainstay, wrap behind the rear wheel.
#define CODYS_BIKE_FRAME_LED_COUNT 50
#define CODYS_BIKE_FRAME_GROUP_SIZE 3

const PanelPixel CODYS_BIKE_FRAME_MAP[CODYS_BIKE_FRAME_LED_COUNT] = {
    {255, 255, 3,   0},  // px  0  side A, x 103.4 cm, y 82.6 cm
    {247, 233, 3,  33},  // px  1  side A, x 100.1 cm, y 77.9 cm
    {239, 212, 3,  65},  // px  2  side A, x  96.9 cm, y 73.2 cm
    {231, 190, 3,  98},  // px  3  side A, x  93.6 cm, y 68.5 cm
    {222, 168, 3, 131},  // px  4  side A, x  90.3 cm, y 63.7 cm
    {214, 147, 3, 163},  // px  5  side A, x  87.1 cm, y 59.0 cm
    {206, 125, 3, 196},  // px  6  side A, x  83.8 cm, y 54.3 cm
    {198, 103, 3, 229},  // px  7  side A, x  80.6 cm, y 49.6 cm
    {190,  82, 2,   6},  // px  8  side A, x  77.3 cm, y 44.8 cm
    {182,  60, 2,  39},  // px  9  side A, x  74.0 cm, y 40.1 cm
    {173,  38, 2,  72},  // px 10  side A, x  70.8 cm, y 35.4 cm
    {165,  17, 2, 104},  // px 11  side A, x  67.5 cm, y 30.7 cm
    {156,   0, 2, 142},  // px 12  side A, x  63.7 cm, y 27.0 cm
    {141,   0, 2, 200},  // px 13  side A, x  58.0 cm, y 27.0 cm
    {127,   0, 1,   2},  // px 14  side A, x  52.2 cm, y 27.0 cm
    {113,   0, 1,  60},  // px 15  side A, x  46.5 cm, y 27.0 cm
    { 98,   0, 1, 118},  // px 16  side A, x  40.8 cm, y 27.0 cm
    { 84,   0, 1, 175},  // px 17  side A, x  35.0 cm, y 27.0 cm
    { 69,   0, 1, 233},  // px 18  side A, x  29.3 cm, y 27.0 cm
    { 55,   0, 0,  35},  // px 19  side A, x  23.5 cm, y 27.0 cm
    { 41,   0, 0,  93},  // px 20  side A, x  17.8 cm, y 27.0 cm
    { 26,   0, 0, 150},  // px 21  side A, x  12.1 cm, y 27.0 cm
    { 16,  14, 0, 191},  // px 22  side A, x   8.0 cm, y 30.1 cm
    {  8,  36, 0, 223},  // px 23  side A, x   4.8 cm, y 34.8 cm
    {  0,  58, 0, 255},  // px 24  side A, x   1.6 cm, y 39.6 cm
    {  0,  58, 0, 255},  // px 25  side B, x   1.6 cm, y 39.6 cm
    {  8,  36, 0, 223},  // px 26  side B, x   4.8 cm, y 34.8 cm
    { 16,  14, 0, 191},  // px 27  side B, x   8.0 cm, y 30.1 cm
    { 26,   0, 0, 150},  // px 28  side B, x  12.1 cm, y 27.0 cm
    { 41,   0, 0,  93},  // px 29  side B, x  17.8 cm, y 27.0 cm
    { 55,   0, 0,  35},  // px 30  side B, x  23.5 cm, y 27.0 cm
    { 69,   0, 1, 233},  // px 31  side B, x  29.3 cm, y 27.0 cm
    { 84,   0, 1, 175},  // px 32  side B, x  35.0 cm, y 27.0 cm
    { 98,   0, 1, 118},  // px 33  side B, x  40.8 cm, y 27.0 cm
    {113,   0, 1,  60},  // px 34  side B, x  46.5 cm, y 27.0 cm
    {127,   0, 1,   2},  // px 35  side B, x  52.2 cm, y 27.0 cm
    {141,   0, 2, 200},  // px 36  side B, x  58.0 cm, y 27.0 cm
    {156,   0, 2, 142},  // px 37  side B, x  63.7 cm, y 27.0 cm
    {165,  17, 2, 104},  // px 38  side B, x  67.5 cm, y 30.7 cm
    {173,  38, 2,  72},  // px 39  side B, x  70.8 cm, y 35.4 cm
    {182,  60, 2,  39},  // px 40  side B, x  74.0 cm, y 40.1 cm
    {190,  82, 2,   6},  // px 41  side B, x  77.3 cm, y 44.8 cm
    {198, 103, 3, 229},  // px 42  side B, x  80.6 cm, y 49.6 cm
    {206, 125, 3, 196},  // px 43  side B, x  83.8 cm, y 54.3 cm
    {214, 147, 3, 163},  // px 44  side B, x  87.1 cm, y 59.0 cm
    {222, 168, 3, 131},  // px 45  side B, x  90.3 cm, y 63.7 cm
    {231, 190, 3,  98},  // px 46  side B, x  93.6 cm, y 68.5 cm
    {239, 212, 3,  65},  // px 47  side B, x  96.9 cm, y 73.2 cm
    {247, 233, 3,  33},  // px 48  side B, x 100.1 cm, y 77.9 cm
    {255, 255, 3,   0},  // px 49  side B, x 103.4 cm, y 82.6 cm
};

// Logical rear->front playback order, both sides in mirror:
const uint16_t CODYS_BIKE_FRAME_STREAM_ORDER[CODYS_BIKE_FRAME_LED_COUNT] = {
    24, 25, 23, 26, 22, 27, 21, 28, 20, 29,
    19, 30, 18, 31, 17, 32, 16, 33, 15, 34,
    14, 35, 13, 36, 12, 37, 11, 38, 10, 39,
     9, 40,  8, 41,  7, 42,  6, 43,  5, 44,
     4, 45,  3, 46,  2, 47,  1, 48,  0, 49,
};

#endif // CODYS_BIKE_MAP_H
