// Generated by BMLightsWatch/scripts/generate-catalog.js - do not edit by hand.
// Regenerate after changing palettes/effects in RNUmbrella/constants.ts or
// libraries/BurningManLEDs/LightShow.cpp:
//
//   node BMLightsWatch/scripts/generate-catalog.js

import SwiftUI

/// One selectable palette. `id` is the exact string the firmware matches in
/// `LightShow::paletteNameToId`.
struct BMPalette: Identifiable, Hashable {
    let id: String
    let name: String
    let colors: [Color]
}

/// One selectable effect. `id` is the exact string the firmware matches in
/// `LightShow::effectNameToId`.
struct BMEffect: Identifiable, Hashable {
    let id: String
    let name: String
}

enum BMCatalog {
    static let palettes: [BMPalette] = [
        BMPalette(id: "candy", name: "Candy", colors: [Color(red: 1.000, green: 0.651, blue: 0.102), Color(red: 0.196, green: 0.102, blue: 1.000), Color(red: 1.000, green: 0.102, blue: 0.867), Color(red: 0.102, green: 0.204, blue: 1.000), Color(red: 1.000, green: 0.651, blue: 0.102)]),
        BMPalette(id: "cool", name: "Cool", colors: [Color(red: 0.000, green: 0.000, blue: 1.000), Color(red: 1.000, green: 0.000, blue: 1.000)]),
        BMPalette(id: "cosmicwaves", name: "Cosmic Waves", colors: [Color(red: 1.000, green: 0.102, blue: 0.973), Color(red: 0.196, green: 0.102, blue: 1.000), Color(red: 0.102, green: 1.000, blue: 0.694), Color(red: 0.102, green: 0.204, blue: 1.000), Color(red: 1.000, green: 0.102, blue: 0.973)]),
        BMPalette(id: "earth", name: "Earth", colors: [Color(red: 0.286, green: 0.612, blue: 0.004), Color(red: 0.145, green: 0.541, blue: 0.043), Color(red: 0.055, green: 0.467, blue: 0.165), Color(red: 0.012, green: 0.404, blue: 0.404), Color(red: 0.004, green: 0.341, blue: 0.773)]),
        BMPalette(id: "eblossom", name: "Electric Blossom", colors: [Color(red: 1.000, green: 0.102, blue: 0.973), Color(red: 0.165, green: 1.000, blue: 0.075), Color(red: 1.000, green: 0.102, blue: 0.973), Color(red: 0.165, green: 1.000, blue: 0.075), Color(red: 1.000, green: 0.102, blue: 0.973)]),
        BMPalette(id: "everglow", name: "Everglow", colors: [Color(red: 0.655, green: 0.957, blue: 0.349), Color(red: 0.361, green: 0.714, blue: 0.102), Color(red: 0.259, green: 0.337, blue: 0.055), Color(red: 0.180, green: 0.063, blue: 0.051), Color(red: 0.133, green: 0.020, blue: 0.035)]),
        BMPalette(id: "fatboy", name: "Fatboy", colors: [Color(red: 0.843, green: 0.290, blue: 0.024), Color(red: 0.071, green: 0.024, blue: 0.106), Color(red: 0.004, green: 0.031, blue: 0.118), Color(red: 0.071, green: 0.024, blue: 0.106), Color(red: 0.843, green: 0.290, blue: 0.024)]),
        BMPalette(id: "fireice", name: "Fire/Ice", colors: [Color(red: 0.314, green: 0.008, blue: 0.004), Color(red: 0.808, green: 0.059, blue: 0.004), Color(red: 0.063, green: 0.263, blue: 0.518), Color(red: 0.008, green: 0.082, blue: 0.271), Color(red: 0.004, green: 0.008, blue: 0.016)]),
        BMPalette(id: "fireynight", name: "Firey Night", colors: [Color(red: 0.969, green: 0.141, blue: 0.141), Color(red: 0.404, green: 0.004, blue: 0.031), Color(red: 0.922, green: 0.310, blue: 0.949), Color(red: 0.996, green: 0.110, blue: 0.125), Color(red: 0.655, green: 0.271, blue: 0.988)]),
        BMPalette(id: "flame", name: "Flame", colors: [Color(red: 0.988, green: 0.165, blue: 0.004), Color(red: 0.835, green: 0.259, blue: 0.004), Color(red: 0.012, green: 0.290, blue: 0.004), Color(red: 0.851, green: 0.024, blue: 0.004), Color(red: 0.988, green: 0.165, blue: 0.004)]),
        BMPalette(id: "heart", name: "Heart", colors: [Color(red: 0.137, green: 0.286, blue: 0.278), Color(red: 0.180, green: 0.161, blue: 0.145), Color(red: 0.231, green: 0.071, blue: 0.059), Color(red: 0.180, green: 0.016, blue: 0.035), Color(red: 0.090, green: 0.024, blue: 0.027)]),
        BMPalette(id: "lava", name: "Lava", colors: [Color(red: 0.000, green: 0.000, blue: 0.000), Color(red: 0.557, green: 0.012, blue: 0.004), Color(red: 0.835, green: 0.173, blue: 0.008), Color(red: 1.000, green: 0.612, blue: 0.016), Color(red: 1.000, green: 1.000, blue: 1.000)]),
        BMPalette(id: "meadow", name: "Meadow", colors: [Color(red: 0.047, green: 0.796, blue: 0.639), Color(red: 0.000, green: 0.341, blue: 0.173), Color(red: 0.227, green: 0.714, blue: 0.200), Color(red: 0.514, green: 0.820, blue: 0.039), Color(red: 0.576, green: 0.925, blue: 0.000)]),
        BMPalette(id: "melonball", name: "Melonball", colors: [Color(red: 0.596, green: 0.890, blue: 0.333), Color(red: 0.843, green: 0.957, blue: 0.416), Color(red: 1.000, green: 0.557, blue: 0.220), Color(red: 1.000, green: 0.353, blue: 0.176), Color(red: 0.898, green: 0.141, blue: 0.243)]),
        BMPalette(id: "nebula", name: "Nebula", colors: [Color(red: 0.412, green: 0.000, blue: 0.757), Color(red: 0.035, green: 0.059, blue: 0.475), Color(red: 0.145, green: 0.192, blue: 0.600), Color(red: 0.635, green: 0.133, blue: 0.345), Color(red: 0.000, green: 0.961, blue: 1.000)]),
        BMPalette(id: "oasis", name: "Oasis", colors: [Color(red: 0.063, green: 0.357, blue: 0.075), Color(red: 0.114, green: 0.929, blue: 0.992), Color(red: 0.655, green: 0.271, blue: 0.988)]),
        BMPalette(id: "pinksplash", name: "Pink Splash", colors: [Color(red: 0.557, green: 0.004, blue: 0.063), Color(red: 0.780, green: 0.333, blue: 0.333), Color(red: 0.988, green: 0.678, blue: 0.643), Color(red: 0.878, green: 0.004, blue: 0.106), Color(red: 0.557, green: 0.004, blue: 0.063)]),
        BMPalette(id: "sofia", name: "Sofia", colors: [Color(red: 0.000, green: 0.353, blue: 0.471), Color(red: 0.020, green: 0.224, blue: 0.224), Color(red: 0.137, green: 0.129, blue: 0.071), Color(red: 0.420, green: 0.333, blue: 0.012), Color(red: 0.918, green: 0.635, blue: 0.000)]),
        BMPalette(id: "sunset", name: "Sunset", colors: [Color(red: 0.471, green: 0.000, blue: 0.000), Color(red: 1.000, green: 0.408, blue: 0.000), Color(red: 0.655, green: 0.086, blue: 0.071), Color(red: 0.063, green: 0.000, blue: 0.510), Color(red: 0.000, green: 0.000, blue: 0.627)]),
        BMPalette(id: "sunsetfusion", name: "Sunset Fusion", colors: [Color(red: 1.000, green: 0.102, blue: 0.973), Color(red: 1.000, green: 0.816, blue: 0.102), Color(red: 1.000, green: 0.102, blue: 0.973), Color(red: 1.000, green: 0.816, blue: 0.102), Color(red: 1.000, green: 0.102, blue: 0.973)]),
        BMPalette(id: "trove", name: "Trove", colors: [Color(red: 0.047, green: 0.090, blue: 0.043), Color(red: 0.788, green: 0.686, blue: 0.231), Color(red: 0.463, green: 0.078, blue: 0.106), Color(red: 0.227, green: 0.122, blue: 0.427), Color(red: 0.267, green: 0.529, blue: 0.204)]),
        BMPalette(id: "vivid", name: "Vivid", colors: [Color(red: 0.616, green: 0.969, blue: 0.141), Color(red: 0.525, green: 0.114, blue: 0.992), Color(red: 0.992, green: 0.133, blue: 0.133), Color(red: 0.655, green: 0.271, blue: 0.988)]),
        BMPalette(id: "velvet", name: "Velvet", colors: [Color(red: 0.004, green: 0.310, blue: 0.314), Color(red: 0.004, green: 0.243, blue: 0.243), Color(red: 0.004, green: 0.169, blue: 0.157), Color(red: 0.004, green: 0.106, blue: 0.090), Color(red: 0.004, green: 0.051, blue: 0.039)]),
        BMPalette(id: "vga", name: "VGA", colors: [Color(red: 1.000, green: 1.000, blue: 1.000), Color(red: 0.000, green: 1.000, blue: 0.000), Color(red: 0.000, green: 0.000, blue: 0.000), Color(red: 0.161, green: 0.216, blue: 0.000), Color(red: 0.161, green: 0.000, blue: 0.173)]),
        BMPalette(id: "wave", name: "Wave", colors: [Color(red: 0.000, green: 0.682, blue: 0.769), Color(red: 0.000, green: 0.176, blue: 0.694), Color(red: 0.000, green: 0.878, blue: 1.000), Color(red: 0.024, green: 0.027, blue: 0.961), Color(red: 0.000, green: 0.961, blue: 1.000)]),
        BMPalette(id: "electricdesert", name: "Electric Desert", colors: [Color(red: 1.000, green: 0.918, blue: 0.000), Color(red: 1.000, green: 0.435, blue: 0.000), Color(red: 0.416, green: 0.106, blue: 0.604), Color(red: 0.157, green: 0.208, blue: 0.576), Color(red: 0.000, green: 0.514, blue: 0.561)]),
        BMPalette(id: "psychedelicplaya", name: "Psychedelic Playa", colors: [Color(red: 1.000, green: 0.000, blue: 0.800), Color(red: 1.000, green: 0.400, blue: 0.000), Color(red: 0.000, green: 1.000, blue: 0.800), Color(red: 0.000, green: 0.400, blue: 1.000), Color(red: 0.800, green: 0.000, blue: 1.000)]),
        BMPalette(id: "burningrainbow", name: "Burning Rainbow", colors: [Color(red: 1.000, green: 0.000, blue: 0.000), Color(red: 1.000, green: 1.000, blue: 0.000), Color(red: 0.294, green: 0.000, blue: 0.510), Color(red: 1.000, green: 0.078, blue: 0.576), Color(red: 1.000, green: 0.843, blue: 0.000)]),
        BMPalette(id: "neonnights", name: "Neon Nights", colors: [Color(red: 0.224, green: 1.000, blue: 0.078), Color(red: 1.000, green: 0.000, blue: 0.800), Color(red: 0.000, green: 1.000, blue: 0.918), Color(red: 0.667, green: 1.000, blue: 0.000), Color(red: 1.000, green: 0.000, blue: 0.902)]),
        BMPalette(id: "desertstorm", name: "Desert Storm", colors: [Color(red: 0.957, green: 0.886, blue: 0.847), Color(red: 0.906, green: 0.435, blue: 0.318), Color(red: 0.969, green: 0.698, blue: 0.404), Color(red: 0.949, green: 0.439, blue: 0.349), Color(red: 0.596, green: 0.322, blue: 0.467)]),
        BMPalette(id: "cosmicfire", name: "Cosmic Fire", colors: [Color(red: 1.000, green: 0.435, blue: 0.000), Color(red: 1.000, green: 0.702, blue: 0.000), Color(red: 1.000, green: 0.992, blue: 0.906), Color(red: 0.835, green: 0.000, blue: 0.976), Color(red: 0.000, green: 0.898, blue: 1.000)]),
        BMPalette(id: "alienglow", name: "Alien Glow", colors: [Color(red: 0.224, green: 1.000, blue: 0.078), Color(red: 0.000, green: 1.000, blue: 0.800), Color(red: 0.000, green: 1.000, blue: 0.200), Color(red: 0.800, green: 1.000, blue: 0.000), Color(red: 1.000, green: 0.918, blue: 0.000)]),
        BMPalette(id: "moltenmetal", name: "Molten Metal", colors: [Color(red: 1.000, green: 0.843, blue: 0.000), Color(red: 1.000, green: 0.549, blue: 0.000), Color(red: 0.698, green: 0.133, blue: 0.133), Color(red: 0.663, green: 0.663, blue: 0.663), Color(red: 0.412, green: 0.412, blue: 0.412)]),
        BMPalette(id: "purpleorange", name: "Purple Orange", colors: [Color(red: 0.502, green: 0.000, blue: 1.000), Color(red: 1.000, green: 0.471, blue: 0.000), Color(red: 0.502, green: 0.000, blue: 1.000)]),
        BMPalette(id: "orangepurple", name: "Orange Purple", colors: [Color(red: 1.000, green: 0.471, blue: 0.000), Color(red: 0.502, green: 0.000, blue: 1.000), Color(red: 1.000, green: 0.471, blue: 0.000)]),
    ]

    static let effects: [BMEffect] = [
        BMEffect(id: "pstream", name: "Palette Stream"),
        BMEffect(id: "pcycle", name: "Palette Cycle"),
        BMEffect(id: "pulse_wave", name: "Pulse Wave"),
        BMEffect(id: "meteor_shower", name: "Meteor Shower"),
        BMEffect(id: "fire_plasma", name: "Fire Plasma"),
        BMEffect(id: "kaleidoscope", name: "Kaleidoscope"),
        BMEffect(id: "rainbow_comet", name: "Rainbow Comet"),
        BMEffect(id: "matrix_rain", name: "Matrix Rain"),
        BMEffect(id: "plasma_clouds", name: "Plasma Clouds"),
        BMEffect(id: "lava_lamp", name: "Lava Lamp"),
        BMEffect(id: "aurora_borealis", name: "Aurora Borealis"),
        BMEffect(id: "lightning_storm", name: "Lightning Storm"),
        BMEffect(id: "color_explosion", name: "Color Explosion"),
        BMEffect(id: "spiral_galaxy", name: "Spiral Galaxy"),
        BMEffect(id: "cradial", name: "Color Radial"),
        BMEffect(id: "cwheel", name: "Color Wheel"),
        BMEffect(id: "speedo", name: "Speedometer"),
        BMEffect(id: "pstat", name: "Position Status"),
        BMEffect(id: "off", name: "Off"),
    ]

    /// Phone-app spellings that mean the same palette to us.
    private static let paletteAliases: [String: String] = [:]

    /// Phone-app spellings that mean the same effect to us.
    private static let effectAliases: [String: String] = [:]

    static func palette(id: String) -> BMPalette? {
        let key = paletteAliases[id] ?? id
        return palettes.first { $0.id == key }
    }

    static func effect(id: String) -> BMEffect? {
        let key = effectAliases[id] ?? id
        return effects.first { $0.id == key }
    }
}
