// GENERATED by scripts/generate-catalog.js - do not edit.
// Sources: RNUmbrella/constants.ts (names, colors, slider ranges) and
// libraries/BurningManLEDs/src/LightShow.cpp (the wire id strings).
#pragma once
#include <stdint.h>

struct BmPalette {
  const char* id;    // exact string LightShow::paletteNameToId matches
  const char* name;
  const uint8_t (*colors)[3];  // evenly spaced gradient stops
  uint8_t count;
};

// One adjustable effect parameter: the BLE command that sets it (int32 LE
// payload) and the slider range the app uses. Values index PARAM_VALUES via
// code - PARAM_CODE_BASE.
struct BmParamDef {
  uint8_t code;
  const char* name;
  int16_t minV, maxV, defV;
};

constexpr uint8_t FX_NEEDS_GPS = 0x01;     // hidden unless status gps=true
constexpr uint8_t FX_NEEDS_MATRIX = 0x02;  // hidden unless status mtxW>0

struct BmEffect {
  const char* id;    // exact string LightShow::effectNameToId matches
  const char* name;
  uint8_t flags;
  int8_t params[3];  // indices into PARAM_DEFS, -1 empty
};

static const uint8_t PALC_candy[][3] = {{255,166,26},{255,166,26},{50,26,255},{50,26,255},{255,26,221},{255,26,221},{26,52,255},{26,52,255},{255,166,26},{255,166,26}};
static const uint8_t PALC_cool[][3] = {{0,0,255},{255,0,255}};
static const uint8_t PALC_cosmicwaves[][3] = {{255,26,248},{255,26,248},{50,26,255},{50,26,255},{26,255,177},{26,255,177},{26,52,255},{26,52,255},{255,26,248},{255,26,248}};
static const uint8_t PALC_earth[][3] = {{73,156,1},{73,156,1},{37,138,11},{37,138,11},{14,119,42},{14,119,42},{3,103,103},{3,103,103},{1,87,197},{1,87,197}};
static const uint8_t PALC_eblossom[][3] = {{255,26,248},{255,26,248},{42,255,19},{42,255,19},{255,26,248},{255,26,248},{42,255,19},{42,255,19},{255,26,248},{255,26,248}};
static const uint8_t PALC_everglow[][3] = {{167,244,89},{167,244,89},{92,182,26},{92,182,26},{66,86,14},{66,86,14},{46,16,13},{46,16,13},{34,5,9},{34,5,9}};
static const uint8_t PALC_fatboy[][3] = {{215,74,6},{74,22,53},{18,6,27},{5,36,85},{1,8,30},{1,8,30},{5,36,85},{18,6,27},{74,22,53},{215,74,6}};
static const uint8_t PALC_fireice[][3] = {{80,2,1},{206,15,1},{242,34,1},{16,67,132},{2,21,69},{1,2,4}};
static const uint8_t PALC_fireynight[][3] = {{247,36,36},{247,36,36},{134,29,253},{134,29,253},{253,34,34},{253,34,34},{103,1,8},{103,1,8},{252,80,65},{252,80,65},{235,79,242},{235,79,242},{255,0,0},{255,0,0},{119,10,242},{119,10,242},{254,28,32},{254,28,32},{232,39,39},{232,39,39},{167,69,252},{167,69,252}};
static const uint8_t PALC_flame[][3] = {{252,42,1},{217,6,1},{213,66,1},{3,74,1},{213,66,1},{217,6,1},{252,42,1}};
static const uint8_t PALC_heart[][3] = {{35,73,71},{35,73,71},{46,41,37},{46,41,37},{59,18,15},{59,18,15},{46,4,9},{46,4,9},{23,6,7},{23,6,7}};
static const uint8_t PALC_lava[][3] = {{0,0,0},{18,0,0},{113,0,0},{142,3,1},{175,17,1},{213,44,2},{174,82,4},{255,115,4},{255,156,4},{255,203,4},{255,255,255},{255,255,255},{255,255,255}};
static const uint8_t PALC_meadow[][3] = {{12,203,163},{12,203,163},{0,92,49},{0,92,49},{0,87,44},{0,87,44},{58,182,51},{58,182,51},{124,255,57},{124,255,57},{131,209,10},{131,209,10},{147,236,0},{147,236,0}};
static const uint8_t PALC_melonball[][3] = {{152,227,85},{152,227,85},{215,244,106},{215,244,106},{255,142,56},{255,142,56},{255,90,45},{255,90,45},{229,36,62},{229,36,62}};
static const uint8_t PALC_nebula[][3] = {{105,0,193},{105,0,193},{9,15,121},{9,15,121},{123,8,137},{123,8,137},{37,49,153},{37,49,153},{162,34,88},{162,34,88},{0,245,255},{0,245,255}};
static const uint8_t PALC_oasis[][3] = {{16,91,19},{16,91,19},{29,237,253},{29,237,253},{29,237,253},{29,237,253},{167,69,252},{167,69,252},{167,69,252},{167,69,252}};
static const uint8_t PALC_pinksplash[][3] = {{142,1,16},{224,1,27},{199,85,85},{252,173,164},{199,85,85},{224,1,27},{142,1,16}};
static const uint8_t PALC_sofia[][3] = {{0,90,120},{0,90,120},{5,57,57},{5,57,57},{35,33,18},{35,33,18},{107,85,3},{107,85,3},{234,162,0},{234,162,0}};
static const uint8_t PALC_sunset[][3] = {{120,0,0},{179,22,0},{255,104,0},{167,22,18},{100,0,103},{16,0,130},{0,0,160}};
static const uint8_t PALC_sunsetfusion[][3] = {{255,26,248},{255,26,248},{255,208,26},{255,208,26},{255,26,248},{255,26,248},{255,208,26},{255,208,26},{255,26,248},{255,26,248}};
static const uint8_t PALC_trove[][3] = {{12,23,11},{8,52,27},{32,142,64},{55,68,24},{190,135,45},{201,175,59},{186,80,20},{220,79,32},{184,33,14},{137,16,15},{118,20,27},{79,16,35},{67,8,38},{22,9,42},{11,3,34},{58,31,109},{186,49,83},{182,25,55},{39,144,100},{15,81,132},{68,135,52}};
static const uint8_t PALC_vivid[][3] = {{157,247,36},{157,247,36},{134,29,253},{134,29,253},{253,34,34},{253,34,34},{167,69,252},{167,69,252},{167,69,252},{167,69,252}};
static const uint8_t PALC_velvet[][3] = {{1,79,80},{1,79,80},{1,62,62},{1,62,62},{1,43,40},{1,43,40},{1,27,23},{1,27,23},{1,13,10},{1,13,10}};
static const uint8_t PALC_vga[][3] = {{255,255,255},{120,133,123},{255,0,0},{255,255,0},{0,255,0},{0,255,255},{0,0,255},{255,0,255},{0,0,0},{41,55,44},{41,0,0},{41,55,0},{0,55,0},{0,55,44},{0,0,44},{41,0,44}};
static const uint8_t PALC_wave[][3] = {{0,174,196},{0,174,196},{255,0,254},{255,0,254},{0,45,177},{0,45,177},{219,20,20},{219,20,20},{0,22,255},{0,22,255},{0,224,255},{0,224,255},{255,0,254},{255,0,254},{6,7,245},{6,7,245},{2,57,252},{2,57,252},{0,245,255},{0,245,255}};
static const uint8_t PALC_electricdesert[][3] = {{255,234,0},{255,179,0},{255,111,0},{244,67,54},{173,20,87},{106,27,154},{69,39,160},{40,53,147},{21,101,192},{0,131,143}};
static const uint8_t PALC_psychedelicplaya[][3] = {{255,0,204},{255,0,153},{255,102,0},{255,204,0},{204,255,0},{0,255,204},{0,204,255},{0,102,255},{102,0,255},{204,0,255}};
static const uint8_t PALC_burningrainbow[][3] = {{255,0,0},{255,127,0},{255,255,0},{0,255,0},{0,0,255},{75,0,130},{148,0,211},{255,20,147},{255,69,0},{255,215,0}};
static const uint8_t PALC_neonnights[][3] = {{57,255,20},{0,229,238},{255,0,204},{255,251,0},{255,7,58},{0,255,234},{255,0,166},{170,255,0},{0,255,208},{255,0,230}};
static const uint8_t PALC_desertstorm[][3] = {{244,226,216},{233,196,106},{231,111,81},{42,157,143},{38,70,83},{247,178,103},{244,132,95},{242,112,89},{206,106,133},{152,82,119}};
static const uint8_t PALC_cosmicfire[][3] = {{255,111,0},{255,143,0},{255,179,0},{255,214,0},{255,234,0},{255,253,231},{255,23,68},{213,0,249},{101,31,255},{0,229,255}};
static const uint8_t PALC_alienglow[][3] = {{57,255,20},{0,255,234},{0,255,204},{0,255,153},{0,255,102},{0,255,51},{0,255,0},{204,255,0},{255,255,0},{255,234,0}};
static const uint8_t PALC_moltenmetal[][3] = {{255,215,0},{255,179,0},{255,140,0},{255,69,0},{255,0,0},{178,34,34},{139,0,0},{169,169,169},{128,128,128},{105,105,105}};
static const uint8_t PALC_purpleorange[][3] = {{128,0,255},{255,120,0},{128,0,255}};
static const uint8_t PALC_orangepurple[][3] = {{255,120,0},{128,0,255},{255,120,0}};

static const BmPalette PALETTES[] = {
  {"candy", "Candy", PALC_candy, 10},
  {"cool", "Cool", PALC_cool, 2},
  {"cosmicwaves", "Cosmic Waves", PALC_cosmicwaves, 10},
  {"earth", "Earth", PALC_earth, 10},
  {"eblossom", "Electric Blossom", PALC_eblossom, 10},
  {"everglow", "Everglow", PALC_everglow, 10},
  {"fatboy", "Fatboy", PALC_fatboy, 10},
  {"fireice", "Fire/Ice", PALC_fireice, 6},
  {"fireynight", "Firey Night", PALC_fireynight, 22},
  {"flame", "Flame", PALC_flame, 7},
  {"heart", "Heart", PALC_heart, 10},
  {"lava", "Lava", PALC_lava, 13},
  {"meadow", "Meadow", PALC_meadow, 14},
  {"melonball", "Melonball", PALC_melonball, 10},
  {"nebula", "Nebula", PALC_nebula, 12},
  {"oasis", "Oasis", PALC_oasis, 10},
  {"pinksplash", "Pink Splash", PALC_pinksplash, 7},
  {"sofia", "Sofia", PALC_sofia, 10},
  {"sunset", "Sunset", PALC_sunset, 7},
  {"sunsetfusion", "Sunset Fusion", PALC_sunsetfusion, 10},
  {"trove", "Trove", PALC_trove, 21},
  {"vivid", "Vivid", PALC_vivid, 10},
  {"velvet", "Velvet", PALC_velvet, 10},
  {"vga", "VGA", PALC_vga, 16},
  {"wave", "Wave", PALC_wave, 20},
  {"electricdesert", "Electric Desert", PALC_electricdesert, 10},
  {"psychedelicplaya", "Psychedelic Playa", PALC_psychedelicplaya, 10},
  {"burningrainbow", "Burning Rainbow", PALC_burningrainbow, 10},
  {"neonnights", "Neon Nights", PALC_neonnights, 10},
  {"desertstorm", "Desert Storm", PALC_desertstorm, 10},
  {"cosmicfire", "Cosmic Fire", PALC_cosmicfire, 10},
  {"alienglow", "Alien Glow", PALC_alienglow, 10},
  {"moltenmetal", "Molten Metal", PALC_moltenmetal, 10},
  {"purpleorange", "Purple Orange", PALC_purpleorange, 3},
  {"orangepurple", "Orange Purple", PALC_orangepurple, 3},
};
static const int PALETTE_COUNT = 35;

static const BmParamDef PARAM_DEFS[] = {
  {0x0b, "Wave Width", 1, 50, 10},
  {0x0c, "Meteor Count", 1, 20, 5},
  {0x0d, "Trail Length", 1, 30, 10},
  {0x0e, "Heat Variance", 1, 100, 50},
  {0x0f, "Mirror Count", 2, 10, 4},
  {0x10, "Comet Count", 1, 10, 3},
  {0x0d, "Trail Length", 1, 30, 15},
  {0x11, "Drop Rate", 1, 100, 25},
  {0x12, "Cloud Scale", 1, 50, 20},
  {0x13, "Blob Count", 1, 20, 8},
  {0x14, "Wave Count", 1, 15, 6},
  {0x15, "Flash Intensity", 1, 100, 80},
  {0x16, "Flash Frequency (ms)", 100, 5000, 1000},
  {0x17, "Explosion Size", 1, 50, 20},
  {0x18, "Spiral Arms", 2, 10, 4},
  {0x12, "Texture Scale", 1, 50, 8},
  {0x11, "Density", 1, 100, 30},
  {0x0b, "Ripple Width", 1, 50, 6},
  {0x0d, "Trail Length", 1, 30, 12},
  {0x17, "Burst Size", 1, 50, 20},
  {0x0d, "Trail Length", 1, 30, 6},
  {0x0b, "Pulse Width", 1, 50, 10},
  {0x11, "Density", 1, 100, 40},
  {0x10, "Balls", 1, 8, 4},
  {0x0d, "Trail Length", 1, 30, 8},
  {0x12, "Wave Scale", 1, 50, 25},
  {0x0e, "Flame Height", 1, 100, 60},
  {0x11, "Density", 1, 100, 60},
  {0x18, "Spokes", 1, 8, 3},
  {0x11, "Star Density", 1, 100, 50},
  {0x0d, "Tail Length", 1, 30, 10},
  {0x11, "Rain Density", 1, 100, 50},
};
static const int PARAM_DEF_COUNT = 32;

static const BmEffect EFFECTS[] = {
  {"pstream", "Palette Stream", 0, {-1, -1, -1}},
  {"pcycle", "Palette Cycle", 0, {-1, -1, -1}},
  {"pulse_wave", "Pulse Wave", 0, {0, -1, -1}},
  {"meteor_shower", "Meteor Shower", 0, {1, 2, -1}},
  {"fire_plasma", "Fire Plasma", 0, {3, -1, -1}},
  {"kaleidoscope", "Kaleidoscope", 0, {4, -1, -1}},
  {"rainbow_comet", "Rainbow Comet", 0, {5, 6, -1}},
  {"matrix_rain", "Matrix Rain", 0, {7, -1, -1}},
  {"plasma_clouds", "Plasma Clouds", 0, {8, -1, -1}},
  {"lava_lamp", "Lava Lamp", 0, {9, -1, -1}},
  {"aurora_borealis", "Aurora Borealis", 0, {10, -1, -1}},
  {"lightning_storm", "Lightning Storm", 0, {11, 12, -1}},
  {"color_explosion", "Color Explosion", 0, {13, -1, -1}},
  {"spiral_galaxy", "Spiral Galaxy", 0, {14, -1, -1}},
  {"noise_flow", "Noise Flow", 0, {15, -1, -1}},
  {"twinkle", "Twinkle", 0, {16, -1, -1}},
  {"ripple", "Ripple", 0, {17, -1, -1}},
  {"cylon", "Cylon", 0, {18, -1, -1}},
  {"fireworks", "Fireworks", 0, {19, -1, -1}},
  {"chevron_wave", "Chevron Wave", 0, {0, -1, -1}},
  {"chevron_chase", "Chevron Chase", 0, {20, -1, -1}},
  {"chevron_burst", "Chevron Burst", 0, {21, -1, -1}},
  {"chevron_glow", "Chevron Glow", 0, {-1, -1, -1}},
  {"chevron_eq", "Chevron EQ", 0, {-1, -1, -1}},
  {"confetti", "Confetti", 0, {22, -1, -1}},
  {"juggle", "Juggle", 0, {23, -1, -1}},
  {"sinelon", "Sinelon", 0, {24, -1, -1}},
  {"bpm", "BPM", 0, {-1, -1, -1}},
  {"pacifica", "Pacifica", 0, {-1, -1, -1}},
  {"panel_waves", "Panel Waves", 0, {25, -1, -1}},
  {"panel_fire", "Panel Fire", 0, {26, -1, -1}},
  {"panel_rain", "Panel Rain", 0, {27, -1, -1}},
  {"panel_spin", "Panel Spin", 0, {28, -1, -1}},
  {"starfield", "Starfield", 0, {29, -1, -1}},
  {"orbit_comet", "Orbit Comet", 0, {30, -1, -1}},
  {"panel_puddle", "Puddle Rain", 0, {31, -1, -1}},
  {"cradial", "Color Radial", 0, {-1, -1, -1}},
  {"cwheel", "Color Wheel", 0, {-1, -1, -1}},
  {"speedo", "Speedometer", FX_NEEDS_GPS, {-1, -1, -1}},
  {"pstat", "Position Status", FX_NEEDS_GPS, {-1, -1, -1}},
};
static const int EFFECT_COUNT = 40;
