# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'Umbrella' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Umbrella

end

target 'Umbrella Watch App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxBluetoothKit'
  # Pods for Umbrella Watch App

end
